# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=15, verbose_name='\u5ba2\u6237\u540d')),
                ('customer_mobile', models.CharField(max_length=11, verbose_name='\u5ba2\u6237\u624b\u673a')),
                ('is_inspect', models.IntegerField(default=0, max_length=1, verbose_name='\u662f\u5426\u770b\u623f')),
                ('is_deal', models.IntegerField(default=0, max_length=1, verbose_name='\u662f\u5426\u6210\u4ea4')),
                ('deal_contract', models.CharField(max_length=500, verbose_name='\u5408\u540c\u4fe1\u606f')),
            ],
            options={
                'db_table': 'Customers',
                'verbose_name': '\u5ba2\u6e90\u4fe1\u606f',
                'verbose_name_plural': '\u5ba2\u6e90\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('saler', models.CharField(max_length=15, verbose_name='\u5356\u5bb6\u59d3\u540d')),
                ('saler_tel', models.CharField(max_length=8, verbose_name='\u5356\u5bb6\u5ea7\u673a')),
                ('saler_mobile', models.CharField(max_length=11, verbose_name='\u5356\u5bb6\u624b\u673a')),
                ('living_area', models.CharField(max_length=50, verbose_name='\u51fa\u552e\u697c\u76d8\u540d')),
                ('address', models.CharField(max_length=200, verbose_name='\u697c\u76d8\u5730\u5740')),
                ('building_number', models.IntegerField(max_length=2, verbose_name='\u51fa\u552e\u680b\u53f7\u5355\u5143\u53f7')),
                ('floor_number', models.CharField(max_length=11, verbose_name='\u51fa\u552e\u697c\u5c42')),
                ('house_number', models.CharField(max_length=11, verbose_name='\u51fa\u552e\u623f\u95f4\u53f7')),
                ('house_owner', models.CharField(max_length=11, verbose_name='\u623f\u4ea7\u5f52\u5c5e\u4eba')),
                ('is_loan', models.IntegerField(default=0, max_length=1, verbose_name='\u662f\u5426\u8d37\u6b3e')),
                ('decorating', models.CharField(default=0, max_length=1, verbose_name='\u88c5\u4fee\u60c5\u51b5')),
                ('sale_price', models.IntegerField(max_length=8, verbose_name='\u552e\u4ef7')),
            ],
            options={
                'db_table': 'Houses',
                'verbose_name': '\u623f\u4ea7\u4fe1\u606f',
                'verbose_name_plural': '\u623f\u4ea7\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='intention',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.Houses', verbose_name='\u610f\u5411\u623f\u4ea7'),
        ),
    ]
