# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-05 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=15, verbose_name='\u5ba2\u6237\u540d')),
                ('customer_mobile', models.CharField(max_length=11, verbose_name='\u5ba2\u6237\u624b\u673a')),
                ('is_look', models.IntegerField(default=0, verbose_name='\u662f\u5426\u770b\u623f')),
                ('look_time', models.DateTimeField(default=None, verbose_name='\u6700\u540e\u770b\u623f\u65f6\u95f4')),
                ('is_deal', models.IntegerField(default=0, verbose_name='\u662f\u5426\u6210\u4ea4')),
                ('deal_contract', models.ImageField(max_length=500, upload_to=b'', verbose_name='\u5408\u540c\u4fe1\u606f')),
            ],
            options={
                'db_table': 'Customers',
                'verbose_name': '\u5ba2\u6e90\u4fe1\u606f',
                'verbose_name_plural': '\u5ba2\u6e90\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('saler', models.CharField(max_length=15, verbose_name='\u5356\u5bb6\u59d3\u540d')),
                ('saler_mobile', models.CharField(max_length=11, verbose_name='\u5356\u5bb6\u624b\u673a')),
                ('saler_tel', models.CharField(max_length=8, verbose_name='\u5356\u5bb6\u5ea7\u673a')),
                ('living_area', models.CharField(max_length=50, verbose_name='\u51fa\u552e\u697c\u76d8\u540d')),
                ('building_number', models.IntegerField(choices=[(1, b'1\xe6\xa0\x8b'), (2, b'2\xe6\xa0\x8b'), (3, b'3\xe6\xa0\x8b'), (4, b'4\xe6\xa0\x8b'), (5, b'5\xe6\xa0\x8b'), (6, b'6\xe6\xa0\x8b'), (7, b'7\xe6\xa0\x8b'), (8, b'8\xe6\xa0\x8b'), (9, b'9\xe6\xa0\x8b'), (10, b'10\xe6\xa0\x8b'), (11, b'11\xe6\xa0\x8b'), (12, b'12\xe6\xa0\x8b'), (13, b'13\xe6\xa0\x8b'), (14, b'14\xe6\xa0\x8b'), (15, b'15\xe6\xa0\x8b'), (16, b'16\xe6\xa0\x8b'), (17, b'17\xe6\xa0\x8b'), (18, b'18\xe6\xa0\x8b'), (19, b'19\xe6\xa0\x8b'), (20, b'20\xe6\xa0\x8b'), (21, b'21\xe6\xa0\x8b'), (22, b'22\xe6\xa0\x8b'), (23, b'23\xe6\xa0\x8b'), (24, b'24\xe6\xa0\x8b'), (25, b'25\xe6\xa0\x8b'), (26, b'26\xe6\xa0\x8b'), (27, b'27\xe6\xa0\x8b'), (28, b'28\xe6\xa0\x8b'), (29, b'29\xe6\xa0\x8b'), (30, b'30\xe6\xa0\x8b')], verbose_name='\u623f\u4ea7\u680b\u53f7')),
                ('floor_number', models.IntegerField(choices=[(1, b'1\xe5\xb1\x82'), (2, b'2\xe5\xb1\x82'), (3, b'3\xe5\xb1\x82'), (4, b'4\xe5\xb1\x82'), (5, b'5\xe5\xb1\x82'), (6, b'6\xe5\xb1\x82'), (7, b'7\xe5\xb1\x82'), (8, b'8\xe5\xb1\x82'), (9, b'9\xe5\xb1\x82'), (10, b'10\xe5\xb1\x82'), (11, b'11\xe5\xb1\x82'), (12, b'12\xe5\xb1\x82'), (13, b'13\xe5\xb1\x82'), (14, b'14\xe5\xb1\x82'), (15, b'15\xe5\xb1\x82'), (16, b'16\xe5\xb1\x82'), (17, b'17\xe5\xb1\x82'), (18, b'18\xe5\xb1\x82'), (19, b'19\xe5\xb1\x82'), (20, b'20\xe5\xb1\x82'), (21, b'21\xe5\xb1\x82'), (22, b'22\xe5\xb1\x82'), (23, b'23\xe5\xb1\x82'), (24, b'24\xe5\xb1\x82'), (25, b'25\xe5\xb1\x82'), (26, b'26\xe5\xb1\x82'), (27, b'27\xe5\xb1\x82'), (28, b'28\xe5\xb1\x82'), (29, b'29\xe5\xb1\x82'), (30, b'30\xe5\xb1\x82'), (31, b'31\xe5\xb1\x82'), (32, b'32\xe5\xb1\x82'), (33, b'33\xe5\xb1\x82'), (34, b'34\xe5\xb1\x82'), (35, b'35\xe5\xb1\x82'), (36, b'36\xe5\xb1\x82'), (37, b'37\xe5\xb1\x82'), (38, b'38\xe5\xb1\x82')], verbose_name='\u697c\u5c42')),
                ('room_number', models.IntegerField(choices=[(1, b'1\xe5\x8f\xb7'), (2, b'2\xe5\x8f\xb7'), (3, b'3\xe5\x8f\xb7'), (4, b'4\xe5\x8f\xb7'), (5, b'5\xe5\x8f\xb7'), (6, b'6\xe5\x8f\xb7'), (7, b'7\xe5\x8f\xb7'), (8, b'8\xe5\x8f\xb7'), (9, b'9\xe5\x8f\xb7'), (10, b'10\xe5\x8f\xb7'), (11, b'11\xe5\x8f\xb7'), (12, b'12\xe5\x8f\xb7'), (13, b'13\xe5\x8f\xb7'), (14, b'14\xe5\x8f\xb7'), (15, b'15\xe5\x8f\xb7'), (16, b'16\xe5\x8f\xb7'), (17, b'17\xe5\x8f\xb7'), (18, b'18\xe5\x8f\xb7'), (19, b'19\xe5\x8f\xb7'), (20, b'20\xe5\x8f\xb7')], verbose_name='\u623f\u53f7')),
                ('decoration', models.IntegerField(choices=[(1, b'\xe6\xb8\x85\xe6\xb0\xb4'), (2, b'\xe7\xae\x80\xe8\xa3\x85'), (3, b'\xe7\xb2\xbe\xe8\xa3\x85')], verbose_name='\u88c5\u4fee\u60c5\u51b5')),
                ('room_size', models.IntegerField(default=0, verbose_name='\u5efa\u7b51\u9762\u79ef')),
                ('room_type', models.CharField(max_length=50, verbose_name='\u6237\u578b\u63cf\u8ff0')),
                ('house_type', models.IntegerField(choices=[(1, b'\xe9\xab\x98\xe5\xb1\x82'), (2, b'\xe6\xb4\x8b\xe6\x88\xbf'), (3, b'\xe7\x9f\xae\xe5\xb1\x82'), (4, b'\xe8\x81\x94\xe6\x8e\x92'), (5, b'\xe7\x8b\xac\xe6\xa0\x8b'), (6, b'\xe4\xb8\x8d\xe5\xb8\xa6\xe7\x94\xb5\xe6\xa2\xaf\xe6\xb4\x8b\xe6\x88\xbf'), (7, b'\xe4\xb8\x8d\xe5\xb8\xa6\xe7\x94\xb5\xe6\xa2\xaf\xe7\x9f\xae\xe5\xb1\x82')], verbose_name='\u623f\u4ea7\u7c7b\u578b')),
                ('region', models.IntegerField(choices=[(1, b'\xe6\xb1\x9f\xe5\x8c\x97\xe5\x8c\xba'), (2, b'\xe5\x8d\x97\xe5\xb2\xb8\xe5\x8c\xba'), (3, b'\xe4\xb9\x9d\xe9\xbe\x99\xe5\x9d\xa1\xe5\x8c\xba'), (4, b'\xe6\xb8\x9d\xe4\xb8\xad\xe5\x8c\xba'), (5, b'\xe5\xa4\xa7\xe6\xb8\xa1\xe5\x8f\xa3\xe5\x8c\xba'), (7, b'\xe5\xb7\xb4\xe5\x8d\x97\xe5\x8c\xba'), (8, b'\xe6\xb8\x9d\xe5\x8c\x97\xe5\x8c\xba'), (9, b'\xe5\x8c\x97\xe7\xa2\x9a\xe5\x8c\xba')], verbose_name='\u884c\u653f\u533a')),
                ('building_addr', models.CharField(max_length=200, verbose_name='\u697c\u76d8\u5177\u4f53\u5730\u5740')),
                ('house_owner', models.CharField(max_length=11, verbose_name='\u623f\u4ea7\u5f52\u5c5e\u4eba')),
                ('buy_time', models.DateField(verbose_name='\u623f\u4ea7\u8d2d\u4e70\u65f6\u95f4')),
                ('building_time', models.DateField(verbose_name='\u697c\u76d8\u5f00\u76d8\u65f6\u95f4')),
                ('is_loan', models.IntegerField(choices=[(1, b'\xe8\xb4\xb7\xe6\xac\xbe'), (2, b'\xe5\x85\xa8\xe6\xac\xbe')], verbose_name='\u662f\u5426\u8d37\u6b3e')),
                ('sale_price', models.FloatField(verbose_name='\u552e\u4ef7')),
            ],
            options={
                'db_table': 'Houses',
                'verbose_name': '\u623f\u4ea7\u4fe1\u606f',
                'verbose_name_plural': '\u623f\u4ea7\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='customers',
            name='intention',
            field=models.ManyToManyField(to='cmsapp.Houses', verbose_name='\u610f\u5411\u623f\u4ea7'),
        ),
    ]
