# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='inspect_time',
            field=models.DateTimeField(default=None, verbose_name='\u6700\u540e\u770b\u623f\u65f6\u95f4'),
        ),
    ]
