# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_customers_inspect_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houses',
            old_name='address',
            new_name='addr',
        ),
        migrations.AddField(
            model_name='houses',
            name='addr_area',
            field=models.IntegerField(default=1, verbose_name='\u533a\u57df\u4ee3\u7801'),
            preserve_default=False,
        ),
    ]
